analyzer:
  exclude:
    - build/**
    - .dart_tool/**
    - "**/*.g.dart"
    - "**/*.freezed.dart"
    - "**/generated_plugin_registrant.dart"
    - "lib/firebase_options.dart"
  errors:
    invalid_annotation_target: ignore
    missing_required_param: error
    missing_return: error
    must_be_immutable: error
    prefer_const_constructors: ignore
    prefer_final_locals: ignore
    avoid_print: ignore
    avoid_dynamic_calls: error
    dead_null_aware_expression: ignore
    inference_failure_on_function_invocation: ignore
    inference_failure_on_instance_creation: ignore
    inference_failure_on_function_return_type: ignore
    sort_constructors_first: ignore
    avoid_redundant_argument_values: ignore
    unused_import: warning
    unused_local_variable: warning
    unnecessary_cast: warning
    unused_field: warning
  language:
    strict-casts: true
    strict-inference: true
    strict-raw-types: true
linter:
  rules:
    public_member_api_docs: false
    avoid_dynamic_calls: true
    avoid_print: false
    prefer_single_quotes: true
    sort_constructors_first: false
    prefer_const_constructors: false
    avoid_redundant_argument_values: false
    prefer_final_locals: false
    use_super_parameters: true
    unnecessary_statements: true