// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      throw UnsupportedError(
        'DefaultFirebaseOptions have not been configured for web - '
        'you can reconfigure this by running the FlutterFire CLI again.',
      );
    }

    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAfg-_6MyMO_CNZ9R2GUSMbaeudlXV96eY',
    appId: '1:315728939057:android:f618d9cc4e76058c71ed10',
    messagingSenderId: '315728939057',
    projectId: 'feeltrip-app',
    storageBucket: 'feeltrip-app.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCBOwYB6CM2W3WVkyyw0q9y07kx2lIUbu0',
    appId: '1:315728939057:ios:47c50fb9847574d271ed10',
    messagingSenderId: '315728939057',
    projectId: 'feeltrip-app',
    storageBucket: 'feeltrip-app.firebasestorage.app',
    iosBundleId: 'com.example.feeltripApp',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyCkaNBuJLWrtCIpYNLpT9_swU1gypF-c8k',
    appId: '1:315728939057:web:a090011fa62f013c71ed10',
    messagingSenderId: '315728939057',
    projectId: 'feeltrip-app',
    authDomain: 'feeltrip-app.firebaseapp.com',
    storageBucket: 'feeltrip-app.firebasestorage.app',
    measurementId: 'G-J6WGHN9Z3M',
  );
}
